version: '3.8'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: always
    ports:
      - 352:80
    volumes:
      - /var/www/html/vendor
      - ./www:/var/www/html
      - ./config:/usr/local/etc/php
    networks:
      - server
  postgres:
    image: postgres:15.3
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=0352
      - POSTGRES_DB=php
    networks:
      - server
volumes:
  html: {}
  config: {}
networks:
  server:
    driver: "bridge"